### ISSUE TITLE
Jinja2 error

### ISSUE THREAD

**Issue by char16t** [shedskin/shedskin#213]
OS: Ubuntu 15.04 x64

Shed Skin was built from sources:
    pip install -r requirements.txt
    sudo python setup.py install

Jinja2 Error:
    root@s2:~# shedskin test.py
    *** SHED SKIN Python-to-C++ Compiler 0.9.4 *** -
    Copyright 2005-2011 Mark Dufour; License GNU GPL version 3 (See LICENSE)

    [analyzing types..]
    |***************************|100%

    [generating c++ code..]
    Traceback (most recent call last):
      File "/usr/local/bin/shedskin", line 3, in <module>
        shedskin.main()
      File "/usr/local/lib/python2.7/dist-packages/shedskin/__init__.py", line 172,                                                                                 in main
        start(gx, main_module_name)
      File "/usr/local/lib/python2.7/dist-packages/shedskin/__init__.py", line 163,                                                                                 in start
        generate_code(gx)
      File "/usr/local/lib/python2.7/dist-packages/shedskin/cpp.py", line 2709, in g                                                                                enerate_code
        walk(module.ast, gv)
      File "/usr/lib/python2.7/compiler/visitor.py", line 106, in walk
        walker.preorder(tree, visitor)
      File "/usr/lib/python2.7/compiler/visitor.py", line 63, in preorder
        self.dispatch(tree, *args) # XXX *args make sense?
      File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
        return meth(node, *args)
      File "/usr/local/lib/python2.7/dist-packages/shedskin/cpp.py", line 560, in vi                                                                                sitModule
        self.module_cpp(node)
      File "/usr/local/lib/python2.7/dist-packages/shedskin/cpp.py", line 457, in mo                                                                                dule_cpp
        file_top = self.jinja_env.get_template('module.cpp.tpl').render(
      File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791,                                                                                 in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765,                                                                                 in _load_template
        template = self.loader.load(self, name, globals)
      File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in                                                                                 load
        source, filename, uptodate = self.get_source(environment, name)
      File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 178, in                                                                                 get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: module.cpp.tpl

**Comment by bingjin** [comment]
This issue is still present in the latest 0.9.1 version. I have to cp the templates folder in the repo to the site-packages/shedskin folder, to make this error go away. Maybe there is something wrong with setup.py.
