### ISSUE TITLE
macos_not_work

### ISSUE THREAD

**Issue by perfectswpuboy1** [shedskin/shedskin#245]
LLMmatoMacBook-Pro:Downloads llm$ shedskin test.py 
*** SHED SKIN Python-to-C++ Compiler 0.9.4 *** - 
Copyright 2005-2011 Mark Dufour; License GNU GPL version 3 (See LICENSE)

[analyzing types..]
Traceback (most recent call last):
  File "/usr/local/bin/shedskin", line 3, in <module>
    shedskin.main()
  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 172, in main
    start(gx, main_module_name)
  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 161, in start
    analyze(gx, main_module_name)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1409, in analyze
    iterative_dataflow_analysis(gx)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1091, in iterative_dataflow_analysis
    update_progressbar(gx, 0)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1074, in update_progressbar
    gx.progressbar.update(perc)
  File "/Library/Python/2.7/site-packages/progressbar/__init__.py", line 276, in update
    if not self._need_update(): return
  File "/Library/Python/2.7/site-packages/progressbar/__init__.py", line 251, in _need_update
    if self.currval >= self.next_update or self.finished: return True
AttributeError: next_update

**Comment by Arkanosis** [comment]
Hi @perfectswpuboy1, thanks for the report!

This is most likely because you're using `progressbar` instead of `progressbar2`. Shedsdkin depends on `progressbar2` as specified in the `requirements.txt`. Could you please confirm that's the version you're using?

See #243 for more discussion about this.

Thanks again :)

**Comment by perfectswpuboy1** [comment]
@Arkanosis Hi,buddy! I've try to uninstall my progressbar ,and make sure my requirement is ready.But When i user such commond the same error comes out.
LLMmatoMBP:all_in_one_CID_keyGen llm$ shedskin GS3_keygen.py 
*** SHED SKIN Python-to-C++ Compiler 0.9.4 *** - 
Copyright 2005-2011 Mark Dufour; License GNU GPL version 3 (See LICENSE)

[analyzing types..]
Traceback (most recent call last):
  File "/Users/llm/anaconda2/bin/shedskin", line 3, in <module>
    shedskin.main()
  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 172, in main
    start(gx, main_module_name)
  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 161, in start
    analyze(gx, main_module_name)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1409, in analyze
    iterative_dataflow_analysis(gx)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1091, in iterative_dataflow_analysis
    update_progressbar(gx, 0)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1074, in update_progressbar
    gx.progressbar.update(perc)
  File "/Library/Python/2.7/site-packages/progressbar/__init__.py", line 276, in update
    if not self._need_update(): return
  File "/Library/Python/2.7/site-packages/progressbar/__init__.py", line 251, in _need_update
    if self.currval >= self.next_update or self.finished: return True
AttributeError: next_update

**Comment by Arkanosis** [comment]
Hi @perfectswpuboy1 

I'm afraid it's still using `progressbar` instead of `progressbar2`: this looks like the code of the former. I'm confused, though, as AFAIK, neither of them have a `init.py` file (I'm expecting to find the code here in `__init__.py` instead). Maybe you now have both on your system and they are conflicting with each other (as both provide a `progressbar` module)? Maybe anaconda2 comes with outdated packages?

**Comment by perfectswpuboy1** [comment]
@Arkanosis Thanks a lot,I've installed progress bar OK.But another error comes out.I don't know why and how to solve it.
bogon:all_in_one_CID_keyGen llm$ shedskin GS3_keygen.py 
*** SHED SKIN Python-to-C++ Compiler 0.9.4 *** - 
Copyright 2005-2011 Mark Dufour; License GNU GPL version 3 (See LICENSE)

[analyzing types..]
Traceback (most recent call last):
  File "/usr/local/bin/shedskin", line 3, in <module>
    shedskin.main()
  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 172, in main
    start(gx, main_module_name)
  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 161, in start
    analyze(gx, main_module_name)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1409, in analyze
    iterative_dataflow_analysis(gx)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1091, in iterative_dataflow_analysis
    update_progressbar(gx, 0)
  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1065, in update_progressbar
    import progressbar
ImportError: No module named progressbar

**Comment by perfectswpuboy1** [comment]
@Arkanosis Buddy,Thanks a lot.I uninstalled all version of progressbar and reinstall progressbar2,it 's ok.HAHA .Thank you!

**Comment by perfectswpuboy1** [comment]
It 's a great project .
ShedSkin!!!!

**Comment by Arkanosis** [comment]
Hi @perfectswpuboy1

That's great to hear! Have fun! :-)

Thank you!
