### ISSUE TITLE
Shedskin produces unknown error when importing time module

### ISSUE THREAD

**Issue by maartin0** [shedskin/shedskin#267]
I tried to run shedskin with Python 2, and made a simple hello world file, it worked fine. When trying to run a more complex program (where the only import is time), it produces this error, from what I can see it's trying to get the time module. Any ideas? 
```python
Traceback (most recent call last):

  File "/usr/local/bin/shedskin", line 3, in <module>

    shedskin.main()

  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 172, in main

    start(gx, main_module_name)

  File "/Library/Python/2.7/site-packages/shedskin/__init__.py", line 161, in start

    analyze(gx, main_module_name)

  File "/Library/Python/2.7/site-packages/shedskin/infer.py", line 1386, in analyze

    gx.main_module = graph.parse_module(module_name, gx)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 1672, in parse_module

    mv.dispatch(module.ast)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 131, in dispatch

    ASTVisitor.dispatch(self, node, *args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/compiler/visitor.py", line 57, in dispatch

    return meth(node, *args)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 398, in visitModule

    self.visit(n)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 131, in dispatch

    ASTVisitor.dispatch(self, node, *args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/compiler/visitor.py", line 57, in dispatch

    return meth(node, *args)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 589, in visitFrom

    module = self.import_modules(node.modname, node, True)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 563, in import_modules

    module = self.import_module(subname, subname, node, fake)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 570, in import_module

    module = self.analyze_module(name, pseudonym, node, fake)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 627, in analyze_module

    module = parse_module(name, self.gx, getmv().module, node)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 1672, in parse_module

    mv.dispatch(module.ast)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 131, in dispatch

    ASTVisitor.dispatch(self, node, *args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/compiler/visitor.py", line 57, in dispatch

    return meth(node, *args)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 393, in visitModule

    self.visit(ClassNode(dummy, [], None, Pass()))

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 131, in dispatch

    ASTVisitor.dispatch(self, node, *args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/compiler/visitor.py", line 57, in dispatch

    return meth(node, *args)

  File "/Library/Python/2.7/site-packages/shedskin/graph.py", line 1451, in visitClass

    if not getmv().module.builtin and not node in getmv().classnodes:

AttributeError: ModuleVisitor instance has no attribute 'classnodes'```

**Comment by dstromberg** [comment]
Sadly, shedskin and python2 are both pretty dead.

I'd love to see shedskin ported to python3, but it sounds like that isn't going to happen.

**Comment by srepmub** [comment]
actually, I'm planning on finally having a good look over the coming months..

**Comment by srepmub** [comment]
(now that python2 is almost as dead as a doornail)

**Comment by srepmub** [comment]
would it be possible to share the code that doesn't compile, or preferrably, a minimized version of it still shows the problem..?

**Comment by maartin0** [comment]
Sorry this thread is almost a year old so I don't think I'm going to be able to help much..

**Comment by srepmub** [comment]
np, alright closing again :-) thanks for reporting and apologies we couldn't help you in time.
