### ISSUE TITLE
fail to compile for python 3.8.1 on windows

### ISSUE THREAD

**Issue by retsyo** [shedskin/shedskin#414]
Months ago, I can use shedskin with python 3.8.1 on windows 10 64 bits as I stated in https://github.com/shedskin/shedskin/issues/342

However, latest cloned shedskin failed to work with python 3.8.1 on windows again( you can read the details in the last part). After some searching I found that k-boikov pointed out "The is_relative_to error is normally a python3.6 issue, please make sure you are running 3.10 or higher" on https://github.com/Significant-Gravitas/Auto-GPT/issues/3660

so which is the minimal version which shedskin supports now?

Thanks

```
e:\prg\py\winpython\python-3.8.1.amd64\Scripts\shedskin.exe build  test
*** SHED SKIN Python-to-C++ Compiler 0.9.8 ***
Copyright 2005-2023 Mark Dufour and contributors; License GNU GPL version 3 (See LICENSE)

Traceback (most recent call last):
  File "e:\prg\py\winpython\python-3.8.1.amd64\Scripts\shedskin-script.py", line 33, in <module>
    sys.exit(load_entry_point('shedskin==0.9.8', 'console_scripts', 'shedskin')())
  File "e:\prg\py\winpython\python-3.8.1.amd64\lib\site-packages\shedskin-0.9.8-py3.8.egg\shedskin\__main__.py", line 10, in run
    Shedskin.commandline()
  File "e:\prg\py\winpython\python-3.8.1.amd64\lib\site-packages\shedskin-0.9.8-py3.8.egg\shedskin\__init__.py", line 368, in commandline
    ss.build()
  File "e:\prg\py\winpython\python-3.8.1.amd64\lib\site-packages\shedskin-0.9.8-py3.8.egg\shedskin\__init__.py", line 165, in build
    cmake.generate_cmakefile(self.gx)
  File "e:\prg\py\winpython\python-3.8.1.amd64\lib\site-packages\shedskin-0.9.8-py3.8.egg\shedskin\cmake.py", line 451, in generate_cmakefile
    if module.filename.is_relative_to(gx.main_module.filename.parent):
AttributeError: 'WindowsPath' object has no attribute 'is_relative_to'
```

**Comment by srepmub** [comment]
3.9 should work (is_relative_to is new in 3.9). I actually use 3.9.2 myself under debian.  perhaps you could try to replace copy-paste is_relative_to into shedskin:

```
    def is_relative_to(self, *other):
        """Return True if the path is relative to another path or False.
        """
        try:
            self.relative_to(*other)
            return True
        except ValueError:
            return False
```

to see if anything else may be broken under 3.8. in CI we only test 3.9-3.11 ATM (probably thinking that the last 3 major releases should be enough). we could add 3.8 there, but since 3.12 should be out in a few months..
