### ISSUE TITLE
Windows Install and Test

### ISSUE THREAD

**Issue by sistemicorp** [shedskin/shedskin#514]
Struggling to install and build test.py on Windows.  I search all issues.  
Using Python 3.12.

I did install `conan==1.62.0`.

The linux instructions have `sudo apt-get install shedskin` which there is no equivalent on Windows.  So I cloned `shedskin` repo.  

Was able to run setup.py, and it seemed to finish,
```
(.venv) C:\git\shedskin>python setup.py install
running install
 ...
Extracting shedskin-0.0.0-py3.12.egg to c:\git\shedskin\.venv\lib\site-packages
c:\git\shedskin\.venv\lib\site-packages\shedskin-0.0.0-py3.12.egg\shedskin\makefile.py:64: SyntaxWarning: invalid escape sequence '\ '
  esc_space = "\ "
Adding shedskin 0.0.0 to easy-install.pth file

Installed c:\git\shedskin\.venv\lib\site-packages\shedskin-0.0.0-py3.12.egg
Processing dependencies for shedskin==0.0.0
Finished processing dependencies for shedskin==0.0.0
```
But cannot run the build,
```
(.venv) C:\git\shedskin>python shedskin build --conan test
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\git\shedskin\shedskin\__main__.py", line 8, in <module>
    from . import Shedskin
ImportError: attempted relative import with no known parent package
```

As a side note, got two warnings when running `setup.py`,
```
(.venv) C:\git\shedskin>python setup.py install
running install
C:\git\shedskin\.venv\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\git\shedskin\.venv\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
```

**Comment by sistemicorp** [comment]
okay, I fixed it, already, needed `-m`,
```
(.venv) C:\git\shedskin>python -m shedskin build --conan test
```

Maybe the docs can be updated, or just close this, this solution is searchable now.

**Comment by sistemicorp** [comment]
Next bump in the road,
```
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: C:/git/shedskin/build
bld_cmd: cmake --build C:\git\shedskin\build
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  1>Checking Build System
  translating test.py to exe
  'shedskin' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: Custom build for 'C:\git\shedskin\build\CMa
keFiles\f0254fdbe7ebff048efd60e26cd13bd8\test.cpp.rule;C:\git\shedskin\CMakeLists.txt' exited with code 9009. [C:\git\shedskin\build\test-exe.vcxproj]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\git\shedskin\shedskin\__main__.py", line 16, in <module>
    run()
  File "C:\git\shedskin\shedskin\__main__.py", line 12, in run
    Shedskin.commandline()
  File "C:\git\shedskin\shedskin\__init__.py", line 406, in commandline
    ss.build()
  File "C:\git\shedskin\shedskin\__init__.py", line 192, in build
    builder.build()
  File "C:\git\shedskin\shedskin\cmake.py", line 691, in build
    self.process(run_tests=False)
  File "C:\git\shedskin\shedskin\cmake.py", line 816, in process
    self.cmake_build(bld_options)
  File "C:\git\shedskin\shedskin\cmake.py", line 671, in cmake_build
    assert os.system(bld_cmd) == 0
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
I think the problem is `'shedskin' is not recognized as an internal or external command`
Digging into it...

**Comment by srepmub** [comment]
sorry for the late reaction! :S and thanks for the feedback.

did you try installing shedskin using 'pip install .'..? using 'setup.py install' is deprecated, hence the warnings.

let's update the documentation for this in any case, since you are not the first to run into this.

**Comment by srepmub** [comment]
sorry I was a bit busy over the past few days. but great to hear you managed to install everything! :) let's keep the issue open to try and avoid these issues in the future. perhaps disable 'setup.py install', and warn about the wrong version of conan.

CBOR sounds interesting! please let us know when you run into any (other) issues with this. might also be an interesting new shedskin example?

**Comment by sistemicorp** [comment]
Next stumbling is on garbage collector...
When I try and compile the source, I get this error,
```
*** SHED SKIN Python-to-C++ Compiler 0.9.9 ***
Copyright 2005-2024 Mark Dufour and contributors; License GNU GPL version 3 (See LICENSE)

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The CXX compiler identification is MSVC 19.37.32822.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Project: cobs_project
Build type: Release

-- Found Python: C:/Users/marti/AppData/Local/Programs/Python/Python312/python.exe (found version "3.12.3") found components: Interpreter Development Development.Module Development.Embed
-- Configuring done (2.4s)
-- Generating done (0.0s)
-- Build files have been written to: C:/git/b15-ShedskinCobs/build
bld_cmd: cmake --build C:\git\b15-ShedskinCobs\build
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  1>Checking Build System
  translating cobs.py to ext
*** SHED SKIN Python-to-C++ Compiler 0.9.9 ***
Copyright 2005-2024 Mark Dufour and contributors; License GNU GPL version 3 (See LICENSE)


  >> processing [---------------------------------] 0%

  >> processing [---------------------------------] 0%

  >> processing [################-----------------] 50%

  >> processing [################-----------------] 50%

  >> processing [#################################] 100%


  [elapsed time: 0.50 seconds]
  Building Custom Rule C:/git/b15-ShedskinCobs/CMakeLists.txt
  cobs.cpp
C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\shedskin\lib\builtin.hpp(13,10): fatal  error C1083: Cannot open include file: 'gc/gc_allocator.h': No such file or directory [C:\git\b15-ShedskinCobs\build\cobs-ext.vc
xproj]
  builtin.cpp
C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\shedskin\lib\builtin.hpp(13,10): fatal  error C1083: Cannot open include file: 'gc/gc_allocator.h': No such file or directory [C:\git\b15-ShedskinCobs\build\cobs-ext.vc
xproj]
  Generating Code...
```
I hadn't yet installed the recommended gc, I guess `test.py` doesn't require it.  
Anyways, looking at the recommended gc, https://www.hboehm.info/gc/
Following the instructions here, https://github.com/ivmai/bdwgc?tab=readme-ov-file#cmake
That produced `.lib` but didn't see where the header files were put...
In https://github.com/ivmai/libatomic_ops/blob/master/README_win32.txt
there is other instruction, `Go to the src directory in the distribution and run "nmake -f Makefile.msft check".`,
But `nmake` is not found... and `cmake -G` doesn't do the trick either...

Back in the day (90s) I was a Windows dev... and I hated Linux because it seemed one had to build everything, and so many build problems... last 20 years I try and do most of my work on Linux, because building there is so much better now, and building on Windows seems impossible...

**Comment by sistemicorp** [comment]
My partner works on linux side and he was able to compile.
We benchmarked,
```
pure python cobs.py 0.969s
shedskin module (release) - 3.422s
python module (using C version and setup.py) - 0.534s
```

**Comment by srepmub** [comment]
sorry I can't help too much with windows issues. I only test on a clean windows installation before each release to check that all the tests/examples still pass.. 

good to hear you managed to get it work under linux instead. can I find this 'cobs.py' file online, or would you be willing to share it, so I can have a look at what is going on..?

**Comment by sistemicorp** [comment]
Sorry I took so long to respond...
No, the original py file is not public, and I am not the author of it so i can't share it.  
I did get permission to share the output of shedskin,
```
namespace __cobs__ {


str *__name__;



bytes *enc(bytes *data) {
    bytes *__0, *__1, *__2, *__3, *out;
    __ss_int i;

    out = new bytes("");
    data = (data)->__add__(new bytes("\000", 1));

    while ((len(data)>__ss_int(0))) {
        i = data->index(new bytes("\000", 1));
        if ((i>=__ss_int(254))) {
            __0 = ((out)->__add__(__bytes((new tuple<__ss_int>(1,__ss_int(255))))))->__add__(data->__slice__(__ss_int(2), __ss_int(0), __ss_int(254), __ss_int(0)));
            __1 = data->__slice__(__ss_int(1), __ss_int(254), __ss_int(0), __ss_int(0));
            out = __0;
            data = __1;
            if (__eq(data, new bytes("\000", 1))) {
                break;
            }
        }
        else {
            __2 = ((out)->__add__(__bytes((new tuple<__ss_int>(1,(i+__ss_int(1)))))))->__add__(data->__slice__(__ss_int(2), __ss_int(0), i, __ss_int(0)));
            __3 = data->__slice__(__ss_int(1), (i+__ss_int(1)), __ss_int(0), __ss_int(0));
            out = __2;
            data = __3;
        }
    }
    return out;
}

bytes *dec(bytes *data) {
    bytes *__4, *__5, *out, *seg;
    __ss_int code;
    __ss_bool __6, __7;

    out = new bytes("");

    while ((len(data)>__ss_int(0))) {
        code = data->__getitem__(__ss_int(0));
        __4 = data->__slice__(__ss_int(3), __ss_int(1), code, __ss_int(0));
        __5 = data->__slice__(__ss_int(1), code, __ss_int(0), __ss_int(0));
        seg = __4;
        data = __5;
        if (((code==__ss_int(255)) and (len(data)==__ss_int(0)))) {
            seg = (seg)->__iadd__(new bytes("\000", 1));
        }
        else {
            if ((code<__ss_int(255))) {
                seg = (seg)->__iadd__(new bytes("\000", 1));
            }
        }
        out = (out)->__iadd__(seg);
    }
    return out->__slice__(__ss_int(2), __ss_int(0), (-__ss_int(1)), __ss_int(0));
}

void __init() {
    __name__ = new str("cobs");

}

} // module namespace
```
And a few comments,
- compile output was riddled with 184 warnings for files in skedskin/lib/builtin/....
- The compiled code for cobs is quite readable - and also going to be much slower than the C version (too many calls to new and _add_ and _slice_, ...)

**Comment by srepmub** [comment]
thank you for getting back! you are right, all the calls to slice/add (and perhaps index) will be quite slow or even slower after compilation. but the calls to 'new' should be mostly optimized away by shedskin.. shedskin caches 1-length strings so you can work with characters without a call to 'new' each time. for bytes, apparently, that is not the case at the moment. I will fix this shortly!

would it be possible to share the mentioned warnings?

**Comment by srepmub** [comment]
okay, pushed the 1-length bytes optimization. this should save quite a few calls to 'new'. the call to 'index' may also be suboptimal at the moment. will check it out.

**Comment by srepmub** [comment]
btw note there are public cobs implementations in python, with some optimizations such as using a bytearray:

https://github.com/cmcqueen/cobs-python/blob/main/src/cobs/cobs/_cobs_py.py

(this one might work with shedskin with a few changes)

**Comment by srepmub** [comment]
okay when testing a fresh windows install for 0.9.10, I also ran into the problem of not being able to find 'nmake'. 

I think before, nmake and other tools would be added to the path automatically when install msvc build tools. after a bit of fiddling around, I found that you can run 'vcvarsall.bat amd64' from c:\Program Files x86\Microsoft Visual Studio\.... somewhere to initialize a 'visual studio developer command prompt'. this does not however work in a powershell prompt.. so one needs to run this batch file (with correct architecture) from a 'cmd' prompt. doing this, I can again compile test.py (using shedskin build --conan test.py -> don't forget --conan as in the documentation! this is required on windows to automatically pull in libgc and libpcre).

anyway, reopening this issue to document this step.

**Comment by srepmub** [comment]
next time I tried this it worked out-of-the-box again..

**Comment by srepmub** [comment]
added a note to the docs in any case.
